### PR TITLE
Adding the PR template

### PR DESCRIPTION
**Pull request by despino-streaver**
## Description

I am adding a PR template to the repository.

## Related ticket

https://www.notion.so/streaver/Add-a-PR-Template-432a1c7587904db6b4519445f6d53e51?pvs=4

## Further explanation

The PR template is added to the docs folder in the repository.

### CODE REVIEW

**Review by atalagorria — APPROVED** [review]
It looks good! We also have [this example](https://www.notion.so/streaver/Code-Reviews-2dc6ad88c76543f58a15c9e09c1189a6?pvs=4#3679dcd8a9434a6b9b273e50c698dff4) where we define a more detailed template. We don't need that kind of template here, but I want to let you know we have it.

**Comment by atalagorria** [comment]
I also wanted to mention that in the README, we have defined a way of naming the branches and commits; it would be nice if we could follow it next time. What do you think? 
https://github.com/streaver/despino-onboarding-nextjs?tab=readme-ov-file#workflow

**Comment by despino-streaver** [comment]
> I also wanted to mention that in the README, we have defined a way of naming the branches and commits; it would be nice if we could follow it next time. What do you think? https://github.com/streaver/despino-onboarding-nextjs?tab=readme-ov-file#workflow

Perfect! I must say I didn't noticed it, my bad.

**Comment by despino-streaver** [comment]
> I also wanted to mention that in the README, we have defined a way of naming the branches and commits; it would be nice if we could follow it next time. What do you think? https://github.com/streaver/despino-onboarding-nextjs?tab=readme-ov-file#workflow

In fact, I'll close this PR and generate a new branch following the branching standard defined there.

**Pull request closed without merging**
